"""Pure hook-stub renderer (no Ghidra/JVM imports).

Turns call-site evidence (stack args, convention, register clobbers) into a
ready-to-adapt hook stub in Zig or C. Everything here is string generation
from plain data, so it is unit-testable without a JVM.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

# Convention normalization → per-language spellings.
_ZIG_CALLCONV = {
    "cdecl": ".C",
    "stdcall": ".Stdcall",
    "thiscall": ".thiscall",
    "fastcall": ".fastcall",
    "win64": ".win64",
}
_C_CALLCONV = {
    "cdecl": "__cdecl",
    "stdcall": "__stdcall",
    "thiscall": "__thiscall",
    "fastcall": "__fastcall",
    "win64": "",
}

# Reserved words that would collide with generated parameter names.
_ZIG_RESERVED = frozenset(
    {
        "align", "anyopaque", "anytype", "asm", "async", "await", "break",
        "const", "defer", "else", "enum", "error", "export", "extern", "fn",
        "for", "if", "inline", "noinline", "opaque", "packed", "pub",
        "return", "struct", "switch", "test", "type", "union",
        "var", "volatile", "while",
    }
)


@dataclass
class StubArg:
    """One argument in the emitted signature."""

    name: str
    type_text: str  # display type ("u32", "*anyopaque", "uint32_t", real type names)
    note: str = ""  # evidence comment, e.g. "[esp+0x04] <- edx"


@dataclass
class StubSpec:
    """Everything the renderer needs."""

    target_name: str
    address: str
    language: str  # "zig" | "c"
    convention: str  # normalized: cdecl|stdcall|thiscall|fastcall|win64|unknown
    convention_label: str  # as-found label, may carry a "?" for inferred
    args: list[StubArg] = field(default_factory=list)
    return_type: str | None = None  # None → i32/int default
    clobbered_volatile: list[str] = field(default_factory=list)
    clobbered_non_volatile: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


def normalize_convention(raw: str | None, pointer_size: int) -> str:
    """Map a convention label to a normalized key."""
    conv = (raw or "").lower().replace("?", "").strip().lstrip("_").replace(" ", "")
    if conv in _ZIG_CALLCONV:
        return conv
    if "vectorcall" in conv:
        return "fastcall"  # closest safe analogue for a stub
    if conv:
        return "unknown"
    return "win64" if pointer_size == 8 else "cdecl"


def _sanitize_ident(name: str) -> str:
    ident = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if not ident or ident[0].isdigit():
        ident = f"_{ident}"
    return ident


def _zig_ident(name: str) -> str:
    ident = _sanitize_ident(name)
    if ident in _ZIG_RESERVED:
        ident = f"{ident}_"
    return ident


def _default_int_type(language: str, pointer_size: int) -> str:
    if language == "zig":
        return "u64" if pointer_size == 8 else "u32"
    return "uint64_t" if pointer_size == 8 else "uint32_t"


def _ptr_type(language: str) -> str:
    return "*anyopaque" if language == "zig" else "void *"


def arg_type_from_evidence(
    resolved_source: str | None, language: str, pointer_size: int
) -> str:
    """Best-effort type for an evidence-backed argument.

    An address-of resolution (``&[sp+0xNN]``) means the argument is a
    pointer; anything else defaults to a word-sized integer. The agent is
    expected to refine types — the stub says so in its header.
    """
    if resolved_source and resolved_source.startswith("&"):
        return _ptr_type(language)
    return _default_int_type(language, pointer_size)


def render_hook_stub(spec: StubSpec) -> str:
    """Render the stub text for the requested language."""
    if spec.language == "zig":
        return _render_zig(spec)
    if spec.language == "c":
        return _render_c(spec)
    raise ValueError(f"Unsupported language '{spec.language}' (expected 'zig' or 'c')")


def _header(spec: StubSpec) -> list[str]:
    lines = [
        f"// Auto-generated by ghidra-nexus for {spec.target_name} @ {spec.address}",
        f"// Convention: {spec.convention_label or spec.convention} "
        "— run verify_port before writing patch bytes.",
        "// Types are evidence-based guesses; refine them against the decompilation.",
    ]
    for w in spec.warnings:
        lines.append(f"// WARNING: {w}")
    return lines


def _clobber_comment(spec: StubSpec) -> list[str]:
    lines = []
    if spec.clobbered_non_volatile:
        lines.append(
            "// Callee clobbers non-volatile registers "
            f"({', '.join(spec.clobbered_non_volatile)}) — save/restore them "
            "around the call if your hook relies on them."
        )
    if spec.clobbered_volatile:
        lines.append(
            f"// Volatile clobbers (no save needed): {', '.join(spec.clobbered_volatile)}"
        )
    return lines


def _render_zig(spec: StubSpec) -> str:
    callconv = _ZIG_CALLCONV.get(spec.convention, ".C")
    ret = spec.return_type or "i32"
    fn_name = f"{_sanitize_ident(spec.target_name)}_fn"

    lines = _header(spec)
    lines.append("pub const " + fn_name + " = *const fn (")
    for arg in spec.args:
        note = f" // {arg.note}" if arg.note else ""
        lines.append(f"    {_zig_ident(arg.name)}: {arg.type_text},{note}")
    lines.append(f") callconv({callconv}) {ret};")
    lines.append("")
    lines.extend(_clobber_comment(spec))
    return "\n".join(lines)


def _render_c(spec: StubSpec) -> str:
    qualifier = _C_CALLCONV.get(spec.convention, "")
    ret = spec.return_type or "int"
    fn_name = f"{_sanitize_ident(spec.target_name)}_fn"

    lines = _header(spec)
    params = ", ".join(
        f"{arg.type_text} {_sanitize_ident(arg.name)}" for arg in spec.args
    ) or "void"
    conv = f"{qualifier} " if qualifier else ""
    lines.append(f"typedef {ret} ({conv}*{fn_name})({params});")
    for arg in spec.args:
        if arg.note:
            lines.append(f"//   {arg.name}: {arg.note}")
    lines.append("")
    lines.extend(_clobber_comment(spec))
    return "\n".join(lines)
