-- schema.sql
--
-- Canonical mirror of the notebook schema. **Read this** for column-level
-- documentation; the actual CREATE statements live in
-- `_migrations/001_initial.sql` and are applied by `Notebook._migrate()`.
--
-- This file is **not** executed; it's documentation. To change the schema,
-- add `_migrations/00N_<name>.sql` and update this mirror.

-- See `_migrations/001_initial.sql` for the foundation schema.
-- See `_migrations/002_breadcrumbs_archive.sql` for the Phase 5 archive table.
